name: Build Examples CHIP Android SO (Test)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: Fetch Android deps
        run: |
          cd $GITHUB_WORKSPACE
          python3 third_party/android_deps/set_up_android_deps.py
      
      - name: Build CHIPTool
        run: |
          cd $GITHUB_WORKSPACE/examples/android/CHIPTool
          chmod +x gradlew
          ./gradlew assembleDebug
     
      - uses: actions/upload-artifact@v4
        with:
          name: chip-so
          path: |
            ${{ github.workspace }}/examples/android/CHIPTool/app/build/**/arm64-v8a/*.so


          
