name: Build CHIP Android SO (Minimal)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    env:
      CHIP_VERSION: v1.5.1.0
      NDK_VERSION: 25.2.9519653

    steps:
      - uses: actions/checkout@v4

      # ✅ 1. 缓存源码（含 submodule）
      - name: Cache CHIP source
        uses: actions/cache@v4
        with:
          path: connectedhomeip
          key: chip-src-${{ env.CHIP_VERSION }}

      - name: Clone CHIP (if needed)
        run: |
          if [ ! -d "connectedhomeip" ]; then
            git clone https://github.com/project-chip/connectedhomeip.git
            cd connectedhomeip
            git checkout $CHIP_VERSION
            git submodule update --init --recursive
          fi

      # ✅ 2. 基础依赖（很快）
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git gcc g++ ninja-build python3 python3-pip unzip curl

      # ✅ 先装 JDK（必须在最前）
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      # ✅ 4. Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Fake Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      # ✅ 5. 缓存 NDK（关键加速点）
      - name: Cache Android NDK
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_HOME }}/ndk
          key: android-ndk-${{ env.NDK_VERSION }}

      - name: Install NDK (if needed)
        run: |
          if [ ! -d "$ANDROID_HOME/ndk/${NDK_VERSION}" ]; then
            sdkmanager "ndk;${NDK_VERSION}"
          fi
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${NDK_VERSION}" >> $GITHUB_ENV

      # ✅ 6. 安装 GN
      - name: Install GN (prebuilt)
        run: |
          curl -L -o gn.zip https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest
          unzip gn.zip -d gn-bin
          chmod +x gn-bin/gn
          echo "$PWD/gn-bin" >> $GITHUB_PATH

      - name: Disable Pigweed (stub file)
        run: |
          cd connectedhomeip
          mkdir -p build_overrides
          echo "# dummy pigweed env" > build_overrides/pigweed_environment.gni

      # - name: Patch Java rules
      #   run: |
      #     cd connectedhomeip
          
      #     python3 - <<'PY'
      #     from pathlib import Path
          
      #     p = Path("build/chip/java/rules.gni")
          
      #     text = p.read_text()
          
      #     text = text.replace(
      #     '''assert(android_sdk_root != "" || matter_enable_java_compilation,
      #            "android_sdk_root must be specified or JAVA_HOME must be set.")''',
      #     '''assert(true)'''
      #     )
          
      #     p.write_text(text)
      #     PY

      - name: Check targets
        run: |
          cd connectedhomeip
          gn ls out/android-arm64 "//src/controller/java/*" || true
          gn ls out/android-arm64 "//src/platform/android/*" || true
          gn ls out/android-arm64 "//examples/android/*"

      # ✅ 8. 构建（无 Java / 无 CIPD）
      - name: Build CHIP SO
        run: |
          cd connectedhomeip

          # 注释 assert
          # sed -i 's/assert(android_sdk_root != "" || matter_enable_java_compilation,/if (false)/g' build/chip/java/rules.gni

          # 把所有包含 java 的行删掉
          # cp BUILD.gn BUILD.gn.bak
          # grep -v "java" BUILD.gn.bak > BUILD.gn

          sed -i 's/-Werror//g' build/chip/java/kotlinc_runner.py

          gn gen out/android-arm64 --args='
            target_os="android"
            target_cpu="arm64"
            android_ndk_root="'$ANDROID_NDK_HOME'"
            android_sdk_root="'$ANDROID_SDK_ROOT'"
            is_debug=false

            # 🔥 关键：关闭 Java/Kotlin（避免编译报错）
            matter_enable_java_compilation=true
            chip_device_platform="android"
            
            # 🔥 关键：关闭 Pigweed 相关
            chip_build_tests=false
            # chip_build_fuzz_tests=false
            # is_component_build=true
          '

          ninja -C out/android-arm64 
          # CHIPController SetupPayloadParser

      - name: Create SO
        run: |
          cd connectedhomeip
          mkdir -p out/shared
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
            -shared \
            -o out/shared/libCHIPController.so \
            -Wl,--whole-archive \
            out/android-arm64/lib/libCHIP.a \
            -Wl,--no-whole-archive \
            -llog \
            -landroid \
            -lz \
            -lc++_shared

      - name: Copy libc++
        run: |
          cp \
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so \
          connectedhomeip/out/shared/

      - name: Create SetupPayloadParser SO
        run: |
          cd connectedhomeip
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
            -shared \
            -o out/shared/libSetupPayloadParser.so \
            -Wl,--whole-archive \
            out/android-arm64/obj/src/setup_payload/lib/libSetupPayload.a \
            -Wl,--no-whole-archive \
            -llog \
            -landroid \
            -lz \
            -lc++_shared

      - name: Find SO
        run: |
          cd connectedhomeip
          echo "===== find so ====="
          # find out -name "*.so"
          find out -type f | grep -E '\.(so|a|jar)$'
          
      # ✅ 9. 上传结果
      - name: Upload SO
        uses: actions/upload-artifact@v4
        with:
          name: chip-so
          path: connectedhomeip/out/shared/*
